version: '3.3'

services:

  admin:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/admin:0.0.1-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9093:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080

  gateway:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/gateway:0.0.1-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9090:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      NACOS_HOST: '192.168.88.87'
      SENTINEL_DASHBOARD_HOST: '192.168.88.87'
#    depends_on:
#      - user

  product:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/product-web:0.0.1-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9092:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      NACOS_HOST: '192.168.88.87'
      MYSQL_HOST: '192.168.88.7'
      MYSQL_PASSWORD: ''
      SENTINEL_DASHBOARD_HOST: '192.168.88.87'
      ADMIN_HOST: 'admin'
      ADMIN_PORT: 8080
    depends_on:
      - admin

  order:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/order-web:0.0.1-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9091:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      NACOS_HOST: '192.168.88.87'
      MYSQL_HOST: '192.168.88.7'
      MYSQL_PASSWORD: ''
      SENTINEL_DASHBOARD_HOST: '192.168.88.87'
      ADMIN_HOST: 'admin'
      ADMIN_PORT: 8080
    depends_on:
      - admin

networks:
  samples:

volumes:
  mydata:
