version: '3.3'

services:

  admin:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/admin:0.0.1-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9093:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080

  user:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/user-web:0.1.3-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9095:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8080
      ADMIN_HOST: 'admin'
      ADMIN_PORT: 8080
    depends_on:
      - admin

  product:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/product-web:0.1.3-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9092:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8080
      ADMIN_HOST: 'admin'
      ADMIN_PORT: 8080
    depends_on:
      - admin

  order:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/order-web:0.1.3-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9091:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8080
      ADMIN_HOST: 'admin'
      ADMIN_PORT: 8080
    depends_on:
      - admin

networks:
  samples:

volumes:
  mydata:
